name: Update ip list

on:
  workflow_dispatch:

  schedule: 
    - cron:  '0 2 1,16 * *'
  
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.x'
          check-latest: true
      - name: Install dependencies
        run:
          pip install netaddr requests

      - name: generate cn iplist
        run:
          python scripts/update_chnip.py

      - name: generate rules
        run: |
          for script in ./scripts/generate/*.py; do
            python "$script" &
          done

      - name: Get current date
        id: date
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update ${{ steps.date.outputs.date }}"
          file_pattern: |
            chnroute.txt
            chnroute-ipv4.txt
            chnroute-ipv6.txt
            cn.rsc
            ipv6.list
            Loon/ruleset/ipv6.list
            chn.acl
            v2ray-config_rule.json
            chnroute.pac